//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentChoices.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPDBEntities : DbContext
    {
        public PPDBEntities()
            : base("name=PPDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<ClassGroups> ClassGroups { get; set; }
        public virtual DbSet<ElectiveSubjectsAndSpecialities> ElectiveSubjectsAndSpecialities { get; set; }
        public virtual DbSet<Files> Files { get; set; }
        public virtual DbSet<FinalChoices> FinalChoices { get; set; }
        public virtual DbSet<StudentChoices> StudentChoices { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<StudentsAndClassGroups> StudentsAndClassGroups { get; set; }
    }
}
